### ISSUE TITLE
UserData

### ISSUE THREAD

**Issue by rtate2** [TriniKwan/CritterCaps#1]
# User Story
User should be able to GET a list of users as well as GET a single user.  

# Acceptance Criteria
**WHEN** the API calls for all users
**THEN** a list of all users shall be returned

# Dev Notes
- A customer should be able to "delete their account", but this should only remove personally identifiable information. This action should not delete the record entirely.
- Create table and seed data
 - Seed  2 customers and 1 seller
- Should be a Sql script checked in to source control that other team members can run

**Comment by LaCollins** [comment]
Data Structure

User
[
Id,
FirstName: string,
LastName: string,
AccountDate: DateTime,
Admin: bool
]
