### ISSUE TITLE
ProductData

### ISSUE THREAD

**Issue by rtate2** [TriniKwan/CritterCaps#2]
# User Story
User should be able to GET a list of products, and GET a single product.

Remember that DELETE doesn't ***have to*** delete data. It needs to take a "delete like" action.

# Acceptance Criteria
**WHEN** the API calls for all products
**THEN** all products will be displayed

**WHEN** the API calls for a single product
**THEN** a single product will be displayed

# Dev Notes
- Create table and seed data
  - Create at least 5 products
  - Should be a Sql script checked in to source control that other team members can run
  - Complete API calls via Dapper

**Comment by LaCollins** [comment]
Data Structure:

Save as a ProductTable sql file.

Products
[
Id
Type: ProductTypeId,
AnimalType: AnimalTypeId,
Title: string,
Description: string,
Quantity: int,
Price: decimal,
ImageUrl: string,
InStock: bool
]

**Comment by LaCollins** [comment]
Save Seed Data as separate SQL query file.
