### ISSUE TITLE
ProductDataType

### ISSUE THREAD

**Issue by rtate2** [TriniKwan/CritterCaps#3]
# User Story
User should be able to GET a list, and GET a single item.

# Acceptance Criteria
**WHEN** the API calls all items
**THEN** all items will be displayed

**WHEN** the API call a single item
**THEN** a single item will be displayed

# Dev Notes
- Create table and seed data
- Create at least 3 product types that fit in with your application theme
- Remember that DELETE doesn't ***have to*** delete data. It needs to take a "delete like" action.
- Should be a Sql script checked in to source control that other team members can run

**Comment by LaCollins** [comment]
Data Structure

ProductType
[
Id,
Category: string,
]
