### ISSUE TITLE
OrderData

### ISSUE THREAD

**Issue by rtate2** [TriniKwan/CritterCaps#4]
# User Story
User should be able to GET a list of orders as well as GET a single order.

# Acceptance Criteria
**WHEN** the API calls all orders
**THEN** all orders will be displayed

**WHEN** the API calls a single order
**THEN** a single order will be displayed

# Dev Notes
- A customer would have a reference to a shopping cart, each completed order would have a reference to a customer.
- Create table and seed data
  - Create the table(s)
  - Create 3 orders with at least 1 line item a piece
  - Possibility of two SQL queries to calculate 'Total Order'
  - Should be a Sql script checked in to source control that other team members can run

**Comment by LaCollins** [comment]
Data structure

May need to rework this or do multiple sql queries to get total

LineItem
[
InvoiceLineId,
OrderId: OrderId,
ProductId: ProductId,
UnitPrice: decimal,
Quantity: int
]


Order
[
Id,
CustomerId: CustomerId,
InvoiceDate,
Total: decimal
PaymentId: PaymentId
]
