### ISSUE TITLE
Seller Dashboard (Edit Function)

### ISSUE THREAD

**Issue by rtate2** [TriniKwan/CritterCaps#40]
***Given*** a seller has sold items

***When*** they navigate to the seller area

***Then*** they should arrive at a dashboard

Dashboard data to display:

- Total Sales
    - Total this month
    - Average per item
- Total Inventory by Category
- Orders that require shipping

# Dev Notes
* When the user logs in, application checks for "administrator" status.
* admin state will get passed down through props
* administrator info will load on Profile page or can create separate Dashboard page that will load admin info
* If an admin is logged in, they can see an edit button on each product card and an "add item" button in the dashboard and product page.
* write update sql method in visual studio for single product
* write add product sql method in visual studio

**Comment by LaCollins** [comment]
* When the user logs in, application checks for "administrator" status.
* admin state will get passed down through props
* If an admin is logged in, they can see an edit button on each product card and an "add item" button in the dashboard and product page.

**Comment by LaCollins** [comment]
* We will have to update the API to allow us to update and add products
* We will have to have to update the Database so that orders have InvoiceDate.
