### ISSUE TITLE
AnimalDataType

### ISSUE THREAD

**Issue by rtate2** [TriniKwan/CritterCaps#6]
# User Story
User should be able to GET a list, and GET a single animal.

# Acceptance Criteria
**WHEN** the API calls all animals
**THEN** all animals will be displayed

**WHEN** the API call a single animal
**THEN** a single animal will be displayed

# Dev Notes
- Create table and seed data
- Create at least 3 animal types that fit in with your application theme
- Remember that DELETE doesn't ***have to*** delete data. It needs to take a "delete like" action.
- Should be a Sql script checked in to source control that other team members can run

**Comment by LaCollins** [comment]
Data structure:

AnimalType
[
Id,
AnimalType: string
]
